const player = {

    "weight": "234",
    "injury_status": null,
    "practice_participation": null,
    "birth_date": "1988-12-01",
    "sport": "nfl",
    "last_name": "Kinne",
    "search_first_name": "gj",
    "player_id": "1",
    "rotoworld_id": null,
    "news_updated": null,
    "birth_state": null,
    "birth_country": null,
    "full_name": "GJ Kinne",
    "height": "6'2\"",
    "espn_id": 15299,
    "stats_id": 399453,
    "injury_body_part": null,
    "status": "Inactive",
    "position": "QB",
    "depth_chart_order": null,
    "team": null,
    "fantasy_data_id": 18,
    "sportradar_id": "a668bd7d-56e5-45ff-a2c8-d618cd1fef95",
    "yahoo_id": 26154,
    "rotowire_id": 8833,
    "college": "Tulsa",
    "metadata": null,
    "search_last_name": "kinne",
    "search_full_name": "gjkinne",
    "injury_start_date": null,
    "high_school": null,
    "search_rank": 9999999,
    "injury_notes": null,
    "fantasy_positions": [
        "QB"
    ],
    "years_exp": 1,
    "pandascore_id": null,
    "hashtag": "#GJKinne-NFL-FA-2",
    "swish_id": null,
    "depth_chart_position": null,
    "practice_description": null,
    "first_name": "GJ",
    "active": false,
    "gsis_id": null,
    "age": 28,
    "number": 2,
    "birth_city": null
}
export default player